**Question No: 2 Using Iris Plant Dataset, write a scratch program in python to train softmax regression that predicts the class of Iris plant.**

Dataset: https://www.kaggle.com/datasets/arshid/iris-flower-dataset


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


# Getting the data from GitHub
github_csv_url = 'https://raw.githubusercontent.com/Rk-Pudasaini/Applied_Machine_Learning/main/Datasets/IRIS.csv'

# Read the Excel file from GitHub into a DataFrame
df = pd.read_csv(github_csv_url)
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [2]:
# Define a mapping of classes to numeric values
class_mapping = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

# Use the map function to replace classes with numeric values
df['species'] = df['species'].map(class_mapping)

df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [3]:
# Split the data into features (X) and target variable (y)
X = df.drop('species', axis=1)
y = df['species']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (mean=0 and variance=1)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [4]:
def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

def cross_entropy_loss(y_true, y_pred):
    m = y_true.shape[0]
    log_probs = -np.log(y_pred[range(m), y_true])
    loss = np.sum(log_probs) / m
    return loss

def gradient_descent(X, y, learning_rate, epochs):
    m, n = X.shape
    k = len(np.unique(y))  # Number of classes
    W = np.zeros((n, k))
    b = np.zeros(k)

    for epoch in range(epochs):
        z = np.dot(X, W) + b
        probabilities = softmax(z)
        loss = cross_entropy_loss(y, probabilities)

        # Compute gradients
        dW = np.dot(X.T, (probabilities - np.eye(k)[y])) / m
        db = np.sum(probabilities - np.eye(k)[y], axis=0) / m

        # Update weights and bias
        W -= learning_rate * dW
        b -= learning_rate * db

        if epoch % 100 == 0:
            print(f'Epoch {epoch}, Loss: {loss}')

    return W, b

# Set hyperparameters
learning_rate = 0.01
epochs = 1000

# Train the softmax regression model
W, b = gradient_descent(X_train, y_train, learning_rate, epochs)


Epoch 0, Loss: 1.0986122886681096
Epoch 100, Loss: 0.6516302243001131
Epoch 200, Loss: 0.5311935748493485
Epoch 300, Loss: 0.473316505177606
Epoch 400, Loss: 0.4372525040148023
Epoch 500, Loss: 0.41162139126945285
Epoch 600, Loss: 0.39188713139309667
Epoch 700, Loss: 0.37584491200671055
Epoch 800, Loss: 0.36228697604897514
Epoch 900, Loss: 0.35049676457222756


In [5]:
# Make predictions on the test set
test_scores = np.dot(X_test, W) + b
test_probabilities = softmax(test_scores)
predictions = np.argmax(test_probabilities, axis=1)


In [6]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Evaluate the model
accuracy = accuracy_score(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)

# Display the results
print(f"Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Accuracy: 0.97

Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [7]:
#implementing softmax regression using the library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load the Iris dataset
github_csv_url = 'https://raw.githubusercontent.com/Rk-Pudasaini/Applied_Machine_Learning/main/Datasets/IRIS.csv'
df = pd.read_csv(github_csv_url)

# Extract features (X) and target variable (y)
X = df.drop('species', axis=1)
y = df['species']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train a softmax regression model
softmax_reg = LogisticRegression(multi_class='multinomial', solver='lbfgs', C=10, random_state=42)
softmax_reg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = softmax_reg.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Display the results
print(f"Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Accuracy: 1.00
Accuracy: 1.00

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

